*&---------------------------------------------------------------------*
*& Include          Z2508R0040_088_TOP
*&---------------------------------------------------------------------*
TABLES : SSCRFIELDS, EKKO, EKPO, LFA1, MAKT.
CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.

DATA : GT_TABLINE TYPE TABLE OF ALSMEX_TABLINE.

TYPES : BEGIN OF TS_EXCEL,
          LIFNR TYPE EKKO-LIFNR,  " VENDOR
          MATNR TYPE EKPO-MATNR,  " MATNR
          MENGE TYPE EKPO-MENGE,  " QUANTITY
          MEINS TYPE EKPO-MEINS,  " UNIT
          NETPR TYPE EKPO-NETPR,  " UNITPRICE
          WAERS TYPE EKKO-WAERS,  " CURRENCY
          WERKS TYPE EKPO-WERKS,  " PLANT
          LGORT TYPE EKPO-LGORT,  " STORAGE LOCATION
        END OF TS_EXCEL,
        TY_EXCEL TYPE TABLE OF TS_EXCEL.

DATA : GS_EXCEL TYPE TS_EXCEL,
       GT_EXCEL TYPE TY_EXCEL.

TYPES : BEGIN OF TS_DISPLAY,
          LIGHT TYPE C LENGTH 4,   " ICON
          LIFNR TYPE EKKO-LIFNR,   " VENDOR
          NAME1 TYPE LFA1-NAME1,   " VENDOR NAME
          MATNR TYPE EKPO-MATNR,   " MATNR
          MAKTX TYPE MAKT-MAKTX,   " MATERIAL NAME
          MENGE TYPE EKPO-MENGE,   " QUANTITY
          MEINS TYPE EKPO-MEINS,   " UNIT
          NETPR TYPE EKPO-NETPR,   " UNITPRICE
          SUM   TYPE EKPO-NETPR,   " SUM
          WAERS TYPE EKKO-WAERS,   " CURRENCY
          WERKS TYPE EKPO-WERKS,   " PLANT
          LGORT TYPE EKPO-LGORT,   " STORAGE LOCATION
          EBELN TYPE EKKO-EBELN,   " PO NUMBER
          MSG   TYPE STRING,       " MESSAGE
        END OF TS_DISPLAY,
        TY_DISPLAY TYPE TABLE OF TS_DISPLAY.

DATA : GS_DISPLAY TYPE TS_DISPLAY,
       GT_DISPLAY TYPE TY_DISPLAY.

TYPES : BEGIN OF TS_LFA1,
          LIFNR TYPE LFA1-LIFNR,
          NAME1 TYPE LFA1-NAME1,
        END OF TS_LFA1,
        TY_LFA1 TYPE TABLE OF TS_LFA1,

        BEGIN OF TS_MAKT,
          MATNR TYPE MAKT-MATNR,
          MAKTX TYPE MAKT-MAKTX,
        END OF TS_MAKT,
        TY_MAKT TYPE TABLE OF TS_MAKT.

DATA : GO_DOCKING  TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GO_ALV_GRID TYPE REF TO CL_GUI_ALV_GRID,
       GS_VARIANT  TYPE DISVARIANT,
       GV_SAVE.

DATA : GT_FCAT TYPE LVC_T_FCAT,
       GS_LAYO TYPE LVC_S_LAYO.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GT_BDCDATA TYPE TABLE OF BDCDATA,    " BDC 데이터 관련
       GT_BDCMSG  TYPE TABLE OF BDCMSGCOLL, " BDC 메시지 관련
       GS_BDCMSG  TYPE BDCMSGCOLL,
       GS_OPT     TYPE CTU_PARAMS.          " BDC 옵션 관련

DATA : GV_EXCLUDE.
