class ZCL_Z_GW_TEAMLIST_088_DPC_EXT definition
  public
  inheriting from ZCL_Z_GW_TEAMLIST_088_DPC
  create public .

public section.
protected section.

  methods ZTEAMLISTSET_CREATE_ENTITY
    redefinition .
  methods ZTEAMLISTSET_GET_ENTITY
    redefinition .
  methods ZTEAMLISTSET_GET_ENTITYSET
    redefinition .
  methods ZTEAMLISTSET_UPDATE_ENTITY
    redefinition .
  methods ZTEAMLISTSET_DELETE_ENTITY
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_Z_GW_TEAMLIST_088_DPC_EXT IMPLEMENTATION.


  METHOD ZTEAMLISTSET_CREATE_ENTITY.

    DATA : LS_ENTITY   LIKE ER_ENTITY,
           LS_TEAMLIST TYPE ZTEAMLIST_088.

    IO_DATA_PROVIDER->READ_ENTRY_DATA(
      IMPORTING
        ES_DATA = LS_ENTITY
    ).

    MOVE-CORRESPONDING LS_ENTITY TO LS_TEAMLIST.

    INSERT ZTEAMLIST_088 FROM LS_TEAMLIST.

  ENDMETHOD.


  METHOD ZTEAMLISTSET_DELETE_ENTITY.

    DATA : WA_TEAMLIST TYPE ZCL_Z_GW_TEAMLIST_088_MPC=>TS_ZTEAMLIST.

    IO_TECH_REQUEST_CONTEXT->GET_CONVERTED_KEYS(
      IMPORTING
        ES_KEY_VALUES = WA_TEAMLIST                 " Entity Key Values - converted
    ).

    DELETE FROM ZTEAMLIST_088
          WHERE DEPCD = WA_TEAMLIST-DEPCD.

  ENDMETHOD.


  METHOD ZTEAMLISTSET_GET_ENTITY.

    DATA : WA_TEAMLIST TYPE ZCL_Z_GW_TEAMLIST_088_MPC=>TS_ZTEAMLIST.

    IO_TECH_REQUEST_CONTEXT->GET_CONVERTED_KEYS(
      IMPORTING
        ES_KEY_VALUES = WA_TEAMLIST                 " Entity Key Values - converted
    ).

    SELECT SINGLE
      DEPCD,
      DNAME
      FROM ZTEAMLIST_088
      INTO CORRESPONDING FIELDS OF @ER_ENTITY
      WHERE DEPCD EQ @WA_TEAMLIST-DEPCD.

  ENDMETHOD.


  METHOD ZTEAMLISTSET_GET_ENTITYSET.

    SELECT DEPCD,
           DNAME
      FROM ZTEAMLIST_088
      INTO CORRESPONDING FIELDS OF TABLE @ET_ENTITYSET.

  ENDMETHOD.


  METHOD ZTEAMLISTSET_UPDATE_ENTITY.

    DATA : WA_TEAMLIST TYPE ZCL_Z_GW_TEAMLIST_088_MPC=>TS_ZTEAMLIST.

    IO_DATA_PROVIDER->READ_ENTRY_DATA(
      IMPORTING
        ES_DATA = WA_TEAMLIST
    ).

    UPDATE ZTEAMLIST_088
      SET DNAME = WA_TEAMLIST-DNAME
    WHERE DEPCD = WA_TEAMLIST-DEPCD.

  ENDMETHOD.
ENDCLASS.
