*&---------------------------------------------------------------------*
*& Include          Z2508R0040_088_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS : S_EKORG FOR EKKO-EKORG NO-EXTENSION NO INTERVALS OBLIGATORY MODIF ID M1,
                   S_EKGRP FOR EKKO-EKGRP NO-EXTENSION NO INTERVALS OBLIGATORY MODIF ID M1,
                   S_BUKRS FOR EKKO-BUKRS NO-EXTENSION NO INTERVALS OBLIGATORY MODIF ID M1.

  PARAMETERS : P_PATH TYPE RLGRAP-FILENAME MODIF ID M1.

  SELECT-OPTIONS : S_WERKS FOR T001W-WERKS NO-EXTENSION NO INTERVALS OBLIGATORY MODIF ID M2,  " 플랜트
                   S_MATNR FOR MARA-MATNR NO-EXTENSION NO INTERVALS MODIF ID M2,              " 자재코드
                   S_LIFRN FOR LFA1-LIFNR NO-EXTENSION NO INTERVALS MODIF ID M2,              " 공급업체
                   S_EBELN FOR EKKO-EBELN NO-EXTENSION NO INTERVALS MODIF ID M2,              " 구매오더번호
                   S_EBELP FOR EKPO-EBELP NO-EXTENSION NO INTERVALS MODIF ID M2,              " 구매오더 품목
                   S_BEDAT FOR EKKO-BEDAT NO-EXTENSION OBLIGATORY MODIF ID M2,                " 증빙일
                   S_DELDT FOR EKET-ELDAT NO-EXTENSION MODIF ID M2.                           " 납품일

  PARAMETERS : P_LOEKZ AS CHECKBOX MODIF ID M2.                                               " 삭제 포함 체크박스

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_MODIF RADIOBUTTON GROUP G1 DEFAULT 'X' USER-COMMAND UC1.
    SELECTION-SCREEN COMMENT POS_LOW(20) TEXT-C01 FOR FIELD P_MODIF.

    PARAMETERS P_CREATE RADIOBUTTON GROUP G1.
    SELECTION-SCREEN COMMENT POS_HIGH(20) TEXT-C02 FOR FIELD P_CREATE.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN : FUNCTION KEY 1.
