PROCESS BEFORE OUTPUT.
  MODULE STATUS_0210.
  MODULE SET_INIT_0210.
  MODULE CLEAR_OK_CODE.

PROCESS AFTER INPUT.
  MODULE EXIT_0210 AT EXIT-COMMAND.
  MODULE USER_COMMAND_0210.

PROCESS ON VALUE-REQUEST.
  FIELD GS_INPUT_SINGLE-MATNR MODULE SET_MATKG.
  FIELD GS_INPUT_SINGLE-SPART MODULE SET_SPART_TXT.
