PROCESS BEFORE OUTPUT.
  MODULE INIT_0120.
  MODULE FILL_SUBSCREEN_DYNNR.
  MODULE MODIFY_SCREEN_0120.
  MODULE CLEAR_OK_CODE.

  CALL SUBSCREEN SUB120 INCLUDING SY-REPID DYNNR.

PROCESS AFTER INPUT.

  CALL SUBSCREEN SUB120 .
  MODULE USER_COMMAND_0120.
