PROCESS BEFORE OUTPUT.
  MODULE STATUS_0200.
  MODULE INIT_0200.
  MODULE CLEAR_OK_CODE.

PROCESS AFTER INPUT.
  MODULE EXIT_0100 AT EXIT-COMMAND.
  MODULE ALV_CHECK_CHANGED_DATA.
  MODULE USER_COMMAND_0200.
