PROCESS BEFORE OUTPUT.
  MODULE INIT_0110.
  MODULE FILL_SUBSCREEN_DYNNR.
  MODULE MODIFY_SCREEN_0110.
  MODULE CLEAR_OK_CODE.

  CALL SUBSCREEN SUB110 INCLUDING SY-REPID
                                  DYNNR.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUB110.
  MODULE USER_COMMAND_0110.
