PROCESS BEFORE OUTPUT.
  MODULE FILL_TABSTRIP_DYNNR.
  MODULE STATUS_0100.
  MODULE CLEAR_OK_CODE.

  CALL SUBSCREEN SUBA INCLUDING SY-REPID DYNNR.

PROCESS AFTER INPUT.
  MODULE EXIT_0100 AT EXIT-COMMAND.

  CALL SUBSCREEN SUBA.

  MODULE GET_ACTIVE_TAB.
  MODULE ALV_CHECK_CHANGED_DATA.
  MODULE USER_COMMAND_0100.
