PROCESS BEFORE OUTPUT.
  MODULE STATUS_0140.
  MODULE INIT_0140.
  MODULE CLEAR_OK_CODE.

PROCESS AFTER INPUT.
  MODULE EXIT_0140 AT EXIT-COMMAND.
  MODULE USER_COMMAND_0140.

PROCESS ON VALUE-REQUEST.
  FIELD ZCC_QUOT-KUNNR MODULE SET_NAME1_0140.
  FIELD ZCC_QUOT-NAME1 MODULE SET_KUNNR_0140.
