PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
  MODULE CLOSE_INPUT.
  MODULE FILL_DYNNR.

  CALL SUBSCREEN SUBA
   INCLUDING SY-CPROG
             DYNNR.

PROCESS AFTER INPUT.
  MODULE EXIT_0100 AT EXIT-COMMAND.
  CALL SUBSCREEN SUBA.

  CHAIN.
    FIELD ZCC_KNA1-KUNNR.
    FIELD ZCC_KNA1-NAME1.
    FIELD ZCC_VBAK-AUART.
    FIELD ZCC_VBAK-VDATU.

    MODULE CHECK_BASIC ON CHAIN-REQUEST.

  ENDCHAIN.

  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD ZCC_KNA1-KUNNR MODULE SET_NAME1.
  FIELD ZCC_KNA1-NAME1 MODULE SET_KUNNR.
