*&---------------------------------------------------------------------*
*& Include          Z2508R0040_088_CLS
*&---------------------------------------------------------------------*
CLASS LCL_EVENT_HANDLER DEFINITION.

  PUBLIC SECTION.
    CLASS-METHODS : HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_COLUMN_ID E_ROW_ID.

ENDCLASS.
CLASS LCL_MODIFICATION_EVENT_HANDLER DEFINITION.

  PUBLIC SECTION.
    CLASS-METHODS : HANDLE_BUTTON_CLICK FOR EVENT BUTTON_CLICK OF CL_GUI_ALV_GRID
      IMPORTING ES_COL_ID ES_ROW_NO,

      ON_TOOLBAR FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT,

      ON_USER_COMMAND FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM.

ENDCLASS.
CLASS LCL_ITEM_EVENT_HANDLER DEFINITION.

  PUBLIC SECTION.
    CLASS-METHODS : ON_TOOLBAR FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT,

      ON_USER_COMMAND FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM,

      ON_DATA_CHANGED FOR EVENT DATA_CHANGED OF CL_GUI_ALV_GRID
        IMPORTING ER_DATA_CHANGED,

      ON_HOTSPOT_CLICK FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
        IMPORTING E_COLUMN_ID E_ROW_ID.

ENDCLASS.
*&---------------------------------------------------------------------*
*& Class (Implementation) lcl_event_handler
*&---------------------------------------------------------------------*
CLASS LCL_EVENT_HANDLER IMPLEMENTATION.

  METHOD HOTSPOT_CLICK.

    CASE E_COLUMN_ID.
      WHEN 'EBELN'.
        READ TABLE GT_DISPLAY INTO DATA(LS_DISPLAY) INDEX E_ROW_ID.

        SET PARAMETER ID 'BES' FIELD LS_DISPLAY-EBELN.
        CALL TRANSACTION 'ME23N' AND SKIP FIRST SCREEN.
    ENDCASE.

  ENDMETHOD.

ENDCLASS.
*&---------------------------------------------------------------------*
*& Class (Implementation) LCL_MODIFICATION_EVENT_HANDLER
*&---------------------------------------------------------------------*
CLASS LCL_MODIFICATION_EVENT_HANDLER IMPLEMENTATION.

  METHOD HANDLE_BUTTON_CLICK.
    PERFORM ALV_CL_BUTTON_CLICK USING ES_COL_ID ES_ROW_NO.
  ENDMETHOD.

  METHOD ON_TOOLBAR.
    PERFORM SET_TOOLBAR CHANGING E_OBJECT.
  ENDMETHOD.

  METHOD ON_USER_COMMAND.
    PERFORM USER_COMMAND USING E_UCOMM.
  ENDMETHOD.

ENDCLASS.
*&---------------------------------------------------------------------*
*& Class (Implementation) LCL_ITEM_EVENT_HANDLER
*&---------------------------------------------------------------------*
CLASS LCL_ITEM_EVENT_HANDLER IMPLEMENTATION.

  METHOD ON_TOOLBAR.
    PERFORM SET_ITEM_TOOLBAR CHANGING E_OBJECT.
  ENDMETHOD.

  METHOD ON_USER_COMMAND.
    PERFORM USER_COMMAND_ITEM USING E_UCOMM.
  ENDMETHOD.

  METHOD ON_DATA_CHANGED.
    PERFORM ALV_HANDER_DATA_CHANGED USING ER_DATA_CHANGED.
  ENDMETHOD.

  METHOD ON_HOTSPOT_CLICK.
    PERFORM HOTSPOT_CLICK_ITEM USING E_COLUMN_ID E_ROW_ID.
  ENDMETHOD.

ENDCLASS.
