*&---------------------------------------------------------------------*
*& Include          ZS4H088R01_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T02.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS : PA_CHECK RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND RADIO_CLICK.
    SELECTION-SCREEN COMMENT (10) TEXT-S01 FOR FIELD PA_CHECK.

    PARAMETERS : PA_CRT RADIOBUTTON GROUP R1.
    SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD PA_CRT.

    PARAMETERS : PA_MOD RADIOBUTTON GROUP R1.
    SELECTION-SCREEN COMMENT (10) TEXT-S03 FOR FIELD PA_MOD.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS : SO_NAME FOR ZS4H088T04-NAME NO INTERVALS NO-EXTENSION MODIF ID M01,  " 이름
  " NO INTERVALS NO-EXTENSION 이후에 SEARCH HELP 걸면 버튼이 안뜬다.. 왜 그런 것인지는 모르겠다..
                   SO_ID   FOR ZS4H088T04-ID   MODIF ID M01.  " ID

SELECTION-SCREEN END OF BLOCK B2.
