*&---------------------------------------------------------------------*
*& Include          Z2508R030_088_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

  PARAMETERS : P_BUKRS TYPE T001-BUKRS OBLIGATORY DEFAULT 4000,  " COMPANY CODE
               P_VBELN TYPE VBAK-VBELN.                          " SALES ORDER

  PARAMETERS : P_PDF AS CHECKBOX DEFAULT ABAP_ON MODIF ID G1.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS : P_OLE RADIOBUTTON GROUP R1 USER-COMMAND UC1.
    SELECTION-SCREEN COMMENT (20) TEXT-C01 FOR FIELD P_OLE.

    PARAMETERS : P_SFORM RADIOBUTTON GROUP R1.
    SELECTION-SCREEN COMMENT (20) TEXT-C02 FOR FIELD P_SFORM.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN : FUNCTION KEY 1.
