*&---------------------------------------------------------------------*
*& Include          Z2508R0040_088_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS : S_EKORG FOR EKKO-EKORG NO-EXTENSION NO INTERVALS OBLIGATORY,
                   S_EKGRP FOR EKKO-EKGRP NO-EXTENSION NO INTERVALS OBLIGATORY,
                   S_BUKRS FOR EKKO-BUKRS NO-EXTENSION NO INTERVALS OBLIGATORY.

  PARAMETERS : P_PATH TYPE RLGRAP-FILENAME DEFAULT 'C:\'.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN : FUNCTION KEY 1.
