*&---------------------------------------------------------------------*
*& Include          Z2603R0050_088_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS : S_DATE  FOR ZBCT0010-TBTCO_STRTDATE,
                   S_JNAME FOR ZBCT0010-TBTCO_JOBNAME,
                   S_PNAME FOR ZBCT0010-PROGNAME.

  PARAMETERS : P_UNAM TYPE ZBCT0010-TBTCO_SDLUNAME.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

  PARAMETERS : P_ALL  RADIOBUTTON GROUP RG1 MODIF ID M1,  "전체
               P_FAIL RADIOBUTTON GROUP RG1 DEFAULT 'X'   "실패
                                           MODIF ID M1,
               P_SUC  RADIOBUTTON GROUP RG1 MODIF ID M1,  "성공
               P_ETC  RADIOBUTTON GROUP RG1 MODIF ID M1.  "기타

SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-T03.

  PARAMETERS : P_SAV RADIOBUTTON GROUP RG2 USER-COMMAND UCOM1, "저장
               P_DIS RADIOBUTTON GROUP RG2 DEFAULT 'X'.        "조회

SELECTION-SCREEN END OF BLOCK B3.
