*&---------------------------------------------------------------------*
*& Include          Z2603R0010_088_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.

  SELECT-OPTIONS : S_ID   FOR SPFLI-CARRID,                              " 항공사 코드
                   S_NAME FOR SCARR-CARRNAME NO INTERVALS NO-EXTENSION,  " 항공사명
                   S_DATE FOR GV_SPMON OBLIGATORY.                       " 예약날짜

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.
  SELECTION-SCREEN BEGIN OF LINE.

    PARAMETERS P_ALL RADIOBUTTON GROUP GR1 DEFAULT 'X'.
    SELECTION-SCREEN COMMENT (15) TEXT-T01 FOR FIELD P_ALL.

    PARAMETERS P_CANC RADIOBUTTON GROUP GR1 .
    SELECTION-SCREEN COMMENT (15) TEXT-T02 FOR FIELD P_CANC.

    PARAMETERS P_CONF RADIOBUTTON GROUP GR1 .
    SELECTION-SCREEN COMMENT (15) TEXT-T03 FOR FIELD P_CONF.

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B2.
