CLASS LHC_ZEDUDV0030_DDL_088 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS CREATE FOR MODIFY
      IMPORTING ENTITIES FOR CREATE ZEDUDV0030_DDL_088.

    METHODS DELETE FOR MODIFY
      IMPORTING KEYS FOR DELETE ZEDUDV0030_DDL_088.

    METHODS UPDATE FOR MODIFY
      IMPORTING ENTITIES FOR UPDATE ZEDUDV0030_DDL_088.

    METHODS READ FOR READ
      IMPORTING KEYS FOR READ ZEDUDV0030_DDL_088 RESULT RESULT.

    METHODS CBA_ITEM FOR MODIFY
      IMPORTING ENTITIES_CBA FOR CREATE ZEDUDV0030_DDL_088\_ITEM.

    METHODS RBA_ITEM FOR READ
      IMPORTING KEYS_RBA FOR READ ZEDUDV0030_DDL_088\_ITEM FULL RESULT_REQUESTED RESULT RESULT LINK ASSOCIATION_LINKS.

ENDCLASS.

CLASS LHC_ZEDUDV0030_DDL_088 IMPLEMENTATION.

  METHOD CREATE.
    BREAK-POINT.
  ENDMETHOD.

  METHOD DELETE.
  ENDMETHOD.

  METHOD UPDATE.
  ENDMETHOD.

  METHOD READ.
  ENDMETHOD.

  METHOD CBA_ITEM.
  ENDMETHOD.

  METHOD RBA_ITEM.
  ENDMETHOD.

ENDCLASS.

CLASS LHC_ZEDUDV0040_DDL_088 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS CREATE FOR MODIFY
      IMPORTING ENTITIES FOR CREATE ZEDUDV0040_DDL_088.

    METHODS DELETE FOR MODIFY
      IMPORTING KEYS FOR DELETE ZEDUDV0040_DDL_088.

    METHODS UPDATE FOR MODIFY
      IMPORTING ENTITIES FOR UPDATE ZEDUDV0040_DDL_088.

    METHODS READ FOR READ
      IMPORTING KEYS FOR READ ZEDUDV0040_DDL_088 RESULT RESULT.

ENDCLASS.

CLASS LHC_ZEDUDV0040_DDL_088 IMPLEMENTATION.

  METHOD CREATE.
  ENDMETHOD.

  METHOD DELETE.
  ENDMETHOD.

  METHOD UPDATE.
  ENDMETHOD.

  METHOD READ.
  ENDMETHOD.

ENDCLASS.

CLASS LSC_ZEDUDV0030_DDL_088 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.

    METHODS CHECK_BEFORE_SAVE REDEFINITION.

    METHODS FINALIZE          REDEFINITION.

    METHODS SAVE              REDEFINITION.

ENDCLASS.

CLASS LSC_ZEDUDV0030_DDL_088 IMPLEMENTATION.

  METHOD CHECK_BEFORE_SAVE.
  ENDMETHOD.

  METHOD FINALIZE.
  ENDMETHOD.

  METHOD SAVE.
  ENDMETHOD.

ENDCLASS.
