*&---------------------------------------------------------------------*
*& Include          ZS4H088R01_TOP
*&---------------------------------------------------------------------*
CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.
TABLES : ZS4H088T02, ZS4H088T03, ZS4H088T04, ZS4H088T05.

TYPES : BEGIN OF TS_DATA,
          ID      TYPE ZS4H088T04-ID,
          BDAY    TYPE ZS4H088T04-BDAY,   " 생년월일
          NAME    TYPE ZS4H088T04-NAME,
          MAIL    TYPE ZS4H088T04-MAIL,
          RDATE   TYPE ZS4H088T05-RDATE,
          REDATE2 TYPE ZS4H088T05-REDATE2,
        END OF TS_DATA,
        TY_DATA TYPE TABLE OF TS_DATA.

*DATA : GS_DATA TYPE TS_DATA,
*       GT_DATA TYPE TY_DATA.

TYPES : BEGIN OF TS_DISPLAY,
          ID      TYPE ZS4H088T04-ID,     " 사용자 ID
          BDAY    TYPE ZS4H088T04-BDAY,   " 생년월일
          NAME    TYPE ZS4H088T04-NAME,   " 사용자 명
          MAIL    TYPE ZS4H088T04-MAIL,   " 전자메일
          RDATE   TYPE ZS4H088T05-RDATE,
          REDATE2 TYPE ZS4H088T05-REDATE2,
          CURRENT TYPE INT4,              " 대여 중인 도서수
          TOTAL   TYPE INT4,              " 전체 대여도서 수
        END OF TS_DISPLAY,
        TY_DISPLAY TYPE TABLE OF TS_DISPLAY.

DATA : GS_DISPLAY TYPE TS_DISPLAY,
       GT_DISPLAY TYPE TY_DISPLAY.

DATA : OK_CODE TYPE SY-UCOMM.

* 100 번 화면을 위한 변수
DATA : GS_FCAT    TYPE LVC_S_FCAT,
       GT_FCAT    TYPE LVC_T_FCAT,
       GS_LAYO    TYPE LVC_S_LAYO,
       GS_VARIANT TYPE DISVARIANT,
       GV_SAVE    TYPE C.

DATA : GO_DOCKING  TYPE REF TO CL_GUI_DOCKING_CONTAINER,
*       GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
       GO_ALV_GRID TYPE REF TO CL_GUI_ALV_GRID.

DATA : GV_ID     TYPE ZS4H088T04-ID,
       GV_NAME   TYPE ZS4H088T04-NAME,
       GV_BDAY   TYPE ZS4H088T04-BDAY,
       GV_MAIL   TYPE ZS4H088T04-MAIL,
       GV_DIALOG,
       GV_COMP.

* 120번 화면을 위한 변수
DATA : GO_DIALOG_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
       GO_ALV_GRID2     TYPE REF TO CL_GUI_ALV_GRID.

DATA : GS_FCAT2 TYPE LVC_S_FCAT,
       GT_FCAT2 TYPE LVC_T_FCAT.

DATA : GO_EVENT TYPE REF TO LCL_EVENT_HANDLER.

DATA : BEGIN OF GS_LIST,
         ISBN_SEQ TYPE C LENGTH 17,          " ISBN-SEQ
         TITLE    TYPE ZS4H088T02-TITLE,
         ISBN     TYPE ZS4H088T03-ISBN,
         SEQ      TYPE ZS4H088T03-SEQ,
         ID       TYPE ZS4H088T05-ID,
         RDATE    TYPE ZS4H088T05-RDATE,
         REDATE2  TYPE ZS4H088T05-REDATE2,
       END OF GS_LIST,
       GT_LIST LIKE TABLE OF GS_LIST.
